### ISSUE TITLE
Improvement in Readme file

### ISSUE THREAD

**Issue by Nimra-1234** [apache/age-viewer#107]
Firstly, node version should be 14.16.0 if someone is not using docker.
And if someone is using Linus(Ubuntu) then that tutorial or some commands should be added in that file.
Suggest me for that so that I can create PR regarding this.

**Comment by sarthak-19** [comment]
An issue : https://github.com/apache/age-viewer/issues/101 is already opened regarding this, improvement in README and documentation, so I guess we can discuss over there.
Also,for the working of Age-Viewer,
1. Recommended node version (14.16.0) is already mentioned in the README. 
2. We are cloning age-viewer repository and to run viewer, commands are same for windows and linux which are again already mentioned in the README. We are only using docker to setup working postgreSQL server with age extension to test viewer by connecting it to the SQL server.
3. We can install the server from source but it is mentioned in detail in Apache Age Readme as it's more relevent to add there, and a link to that is also added in Age-Viewer's documentation.

- Correct me if I'm wrong or misunderstood your issue.

**Comment by Nimra-1234** [comment]
Yeah it is but: 
1. Here in that ^ , might be a misunderstanding that we can node version greater then 14.16.0.
![image](https://user-images.githubusercontent.com/72203032/213249397-60fe9782-a44b-486c-b5d3-d9682af3d82a.png)
2.Though commands are same but the link added is not much self explanatory,we have video tutorial for mac users but not for windows one. We can add https://theundersurfers.netlify.app/age-installation/ that guide instead.

Yes you are right but still I think this should be added. 
Correct me if I'm wrong or misunderstood something.

**Comment by AhmarZaidi** [comment]
Wasn't an issue regarding this already opened 🤔

**Comment by sarthak-19** [comment]
1. This '^14.16.0' means node versions from 14.16.0 to < 15.0.0 will work. I've tested for this and hence added in the documentation, so I'm not seeing where is misunderstanding in that.
2. https://theundersurfers.netlify.app/age-installation/ this link is surely very good, and I was just saying that documentation of age can be improved using this, and it does not belong to age-viewer.

**Comment by Nimra-1234** [comment]
Ok that's great then.But I guess we should replace that link with this one.
