### ISSUE TITLE
Give a warning when using untested node/npm versions

### ISSUE THREAD

**Issue by AhmarZaidi** [apache/age-viewer#110]
## Issue: 
When we install AGE-Viewer on a version of node that is not supported we simply get errors when we run it but not any warning while installing beforehand. Although, it is suggested in the documentation that node versions ^14.16.0 are supported but it is not implemented in code where warnings can be generated by node. 

## Solution:
We can define the `engines` field in the `package.json` and set the range of tested versions there. 
This would give a warning when we try to install while on an untested version.
If the solution is implemented in this way then we can use the `engine-strict flag`. This would simply generate an error on using incompatible versions.
Additionally, if a user changes the node version after installing (say for some other project), then they would get to know very easily that its due to node/npm version incompatibility.

## Links: 
[NPMJS Documentation on Engines in Package.json](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines)   
[Some more info on Package.json and engines](https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html)

**Comment by Nimra-1234** [comment]
Sounds great and this will also help a lot to solve issue easily.

**Comment by AhmarZaidi** [comment]
A warning like this would be issued if we try to install using an incompatible version:
![image](https://user-images.githubusercontent.com/71930390/213268466-6b987148-3829-4092-b1ad-0bbd0ce6dd4c.png)

And if `engine-strict` flag is set to `true` then an error like this is generated:
![image](https://user-images.githubusercontent.com/71930390/213270349-27f4437a-70ad-4975-89f7-d4ee0319f193.png)

**Comment by Nimra-1234** [comment]
This looks more appropriate now.
