### ISSUE TITLE
Unable to connect Apache Age-Viewer to PostgreSQL Database

### ISSUE THREAD

**Issue by moiz697** [apache/age-viewer#112]
I have tried all the steps provided in the documentation to connect Apache Age-Viewer to my PostgreSQL database, but I am still unable to connect. I have verified that the PostgreSQL server is running, the user and password are correct and have the necessary permissions, and the specified port (5455) is open and accessible. But I still can't connect.

I am using the following versions:

Apache Age-Viewer: 14.16.0
PostgreSQL: 12.13

**Comment by Nimra-1234** [comment]
Was it working at first

**Comment by AhmarZaidi** [comment]
@moiz697 can you share the logs of your postgres server. 
If you are using docker then run `docker logs --follow <container_name>`
The `container_name` should be `myPostgresDb` if you are using default setup. 

Also, what error are you getting on the frontend?

**Comment by AhmarZaidi** [comment]
What error are you getting on the frontend?

**Comment by moiz697** [comment]
@AhmarZaidi 
<img width="1646" alt="Screenshot 2023-01-20 at 9 58 29 PM" src="https://user-images.githubusercontent.com/121784313/213759489-1e102a06-c4a3-4781-948e-db9a0b25e733.png">
  yes container name is myPostgresDb

**Comment by moiz697** [comment]
> Was it working at first ?

nope trying for first time

**Comment by sarthak-19** [comment]
First try ```psql -U postgresUser -d postgresDB -p 5455 -h localhost ```  in terminal  from outside and see if it's connecting.

**Comment by moiz697** [comment]
> First try `psql -U postgresUser -d postgresDB -p 5455 -h localhost ` in terminal from outside docker and see if it's connecting.

yes it is connecting to terminal now

**Comment by sarthak-19** [comment]
> yes it is connecting to terminal now

Please share the log, of terminal where you ran age-viewer, once you click on 'Connect' after filling the postgreSQL server, there will be some error showing if unable to connect.

**Comment by AhmarZaidi** [comment]
> @AhmarZaidi <img alt="Screenshot 2023-01-20 at 9 58 29 PM" width="1646" src="https://user-images.githubusercontent.com/121784313/213759489-1e102a06-c4a3-4781-948e-db9a0b25e733.png"> yes container name is myPostgresDb

Okay, what error are you getting on the viewer.

**Comment by moiz697** [comment]
> > @AhmarZaidi <img alt="Screenshot 2023-01-20 at 9 58 29 PM" width="1646" src="https://user-images.githubusercontent.com/121784313/213759489-1e102a06-c4a3-4781-948e-db9a0b25e733.png"> yes container name is myPostgresDb
> 
> Okay, what error are you getting on the viewer.

psql: connection to server at "localhost" (127.0.0.1), port 5455 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5455 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

**Comment by AhmarZaidi** [comment]
@moiz697 Found a similar query [here](https://stackoverflow.com/questions/37307346/is-the-server-running-on-host-localhost-1-and-accepting-tcp-ip-connections) have a look.

**Comment by saadjameel** [comment]
Hello Moiz,
As discussed in meeting, you can close the issue as it is solved.
