### ISSUE TITLE
To discuss and choose between Electron and Node-Webkit for building a desktop application

### ISSUE THREAD

**Issue by shinhanbyeol** [apache/age-viewer#22]

**Comment by shinhanbyeol** [comment]
electron : https://www.electronjs.org/ 
node webkit : https://nwjs.io/

**Comment by shinhanbyeol** [comment]
# desktop application build using electron
I tried to build Age-viewer as a desktop app using electron.js
I got some successful results.
I would like to develop more mature applications

[https://github.com/shinhanbyeol/age-viewer/tree/build/desktop-app-electron/app](https://github.com/shinhanbyeol/age-viewer/tree/build/desktop-app-electron/app)

**Comment by marodins** [comment]
https://www.electronjs.org/docs/latest/development/electron-vs-nwjs

this may be a useful article to compare the frameworks ^

Electron js seems to have better overall support and may be better suited for this desktop app

**Comment by shinhanbyeol** [comment]
@marodins 

My forked branch is ready to set up a build using electron.
I am planning to request a pull request for this content someday.
Please pay a lot of attention to this in the future.

https://github.com/shinhanbyeol/age-viewer/tree/build/desktop-app-electron
