### ISSUE TITLE
Improve node label count metadata query

### ISSUE THREAD

**Issue by JoshInnis** [apache/age-viewer#30]
ANALYZE;
SELECT c.relname AS label, c.reltuples AS cnt
FROM pg_catalog.pg_class c 
JOIN pg_catalog.pg_namespace n 
ON n.oid = c.relnamespace 
WHERE c.relkind = 'r' 
AND n.nspname = 'test';

https://github.com/apache/age-viewer/blob/main/backend/sql/meta_nodes/AGE.sql

**Comment by marodins** [comment]
I have started working on this; both backend and frontend.

**Comment by marodins** [comment]
PR created

**Comment by JoshInnis** [comment]
PR has been merged to master
