### ISSUE TITLE
Problem connecting to age-viewer desktop app

### ISSUE THREAD

**Issue by MJinH** [apache/age-viewer#31]
**Describe the bug**
I'm trying to connect to age-viewer desktop app on Window but I keep getting this message:

C:\Users\mjh19\OneDrive\Desktop\age-viwer-electron\age-viewer\backend\src\tools\AGEParser.js:141
undefined
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\mjh19\OneDrive\Desktop\age-viwer-electron\age-viewer\backend\node_modules\antlr4\src\antlr4\index.js from C:\Users\mjh19\OneDrive\Desktop\age-viwer-electron\age-viewer\backend\src\tools\AGEParser.js not supported.
Instead change the require of index.js in C:\Users\mjh19\OneDrive\Desktop\age-viwer-electron\age-viewer\backend\src\tools\AGEParser.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (C:\Users\mjh19\OneDrive\Desktop\age-viwer-electron\age-viewer\backend\node_modules\@babel\node\lib\_babel-node.js:176:21) {
  code: 'ERR_REQUIRE_ESM'
}

**Additional context**
Adding "type": "commonjs" in package.json doesn't work for me and my current node version is v16.17.0.

**Comment by shinhanbyeol** [comment]
seen as an antlr4 issue. Try to proceed by fixing the antlr4 to 4.9.3
