### ISSUE TITLE
What are DFS(Depth First Search) and BFS(Breadth First Search) algorithms ?

### ISSUE THREAD

**Issue by aked21** [apache/age-viewer#43]

**Comment by MJinH** [comment]
excited to learn about DFS and BFS

**Comment by MJinH** [comment]
I believe DFS (Depth First Search) is a technique for traversing data in graphs and it uses stack data structure. The DFS is usually a recursive algorithm and it pushes the first visited vertices into the stack and if the next vertex does not exist, then the vertices in the stack are popped. Whereas BFS (Breadth First Search) is a technique for traversing the shortest path in graphs and it uses queue data structure.

**Comment by shinhanbyeol** [comment]
Here's some useful information.
https://adrianmejia.com/data-structures-for-beginners-graphs-time-complexity-tutorial/

**Comment by Nimra-1234** [comment]
I have written DFS and BFS along with their traversal that is self explanatory. Hope you'll understand it and found this as good solution.


@aked21 
[DFS and BFS.docx](https://github.com/apache/age-viewer/files/10200848/DFS.and.BFS.docx)

**Comment by Nimra-1234** [comment]
@shinhanbyeol I guess this will help you. If it is so then you can close this issue.

> I have written DFS and BFS along with their traversal that is self explanatory. Hope you'll understand it and found this as good solution.
> 
> @aked21 @shinhanbyeol [DFS and BFS.docx](https://github.com/apache/age-viewer/files/10200848/DFS.and.BFS.docx)

**Comment by shinhanbyeol** [comment]
Thank you.  @Nimra-1234  @MJinH
