### ISSUE TITLE
Age-viewer: Node/edge not displaying labels properly in each label sections

### ISSUE THREAD

**Issue by MJinH** [apache/age-viewer#52]
**Describe the bug**
After [674389a](https://github.com/apache/age-viewer/pull/50/commits/674389ac457e443b1870c711de619e84c8c339cf), select box displays graph names properly, but after running query, 
(ex:
SELECT * 
FROM cypher('graph_name', $$
    CREATE (:Person)
$$) as (v agtype);
)

the label ```Person``` and the number of nodes are not updated in Node Label. 

![Screenshot (46)](https://user-images.githubusercontent.com/97130553/199863028-a1d433de-0333-4d40-914f-5f558feec469.png)

**Desktop (please complete the following information):**
- OS: Window 10 Pro
- Browser chrome
- Version 21H2

**Comment by marodins** [comment]
It looks like this might be a result of incorrectly initializing your graph and data.
The initial query you're running to create the person type needs a name. Screenshots below. Neither #50 or #51 appear to be an issue running locally. 
OS: Ubuntu 22.04
Browser: Chrome
PG: 11.17
![Screenshot from 2022-11-07 14-24-36](https://user-images.githubusercontent.com/67288224/200429318-0752bec3-667a-4a54-b4d5-5f9c369b49ac.png)
![Screenshot from 2022-11-07 14-27-32](https://user-images.githubusercontent.com/67288224/200429340-4429485d-7752-4149-a461-d5ac7fd3bd57.png)

**Comment by MJinH** [comment]
> It looks like this might be a result of incorrectly initializing your graph and data. The initial query you're running to create the person type needs a name. Screenshots below. Neither #51 or [#52](https://github.com/apache/age-viewer/issues/52) appear to be an issue running locally. OS: Ubuntu 22.04 Browser: Chrome PG: 11.17 ![Screenshot from 2022-11-07 14-24-36](https://user-images.githubusercontent.com/67288224/200429318-0752bec3-667a-4a54-b4d5-5f9c369b49ac.png) ![Screenshot from 2022-11-07 14-27-32](https://user-images.githubusercontent.com/67288224/200429340-4429485d-7752-4149-a461-d5ac7fd3bd57.png)

Thanks for your response marodins. After adding a name when creating a node with type, it worked well. I'll close this issue with this comment.
