### ISSUE TITLE
Label (oid) cache corrupted

### ISSUE THREAD

**Issue by MJinH** [apache/age-viewer#83]
**Describe the bug**
This bug happens when refreshing the browser several times.

**Screenshots**
![Screenshot (87)](https://user-images.githubusercontent.com/97130553/208193673-310587e8-a0ea-45f6-930a-867c0b1f9ffb.png)

**Desktop (please complete the following information):**
 - OS: window 10 pro
 - Browser chrome

**Comment by marodins** [comment]
I believe this is caused by the old meta data retrieval query. PR https://github.com/apache/age-viewer/pull/75 still needs to be merged, and should fix this.

**Comment by MJinH** [comment]
#75 is merged.
