### ISSUE TITLE
Frontend frameworks in GO

### ISSUE THREAD

**Issue by saadjameel** [apache/age-viewer#99]
There are many frontend frameworks in Go. 
For desktop I've tried Lorca, it supports good interface but beautifications may get compromised. 

Is there any other suggestion for frontend part for AGE-Viewer keeping in mind this would be a DESKTOP application.

**Comment by shinhanbyeol** [comment]
The way to make it happen right now is to use electron js.
I tried it in my forked repository and I could build it with a desktop app.
Check out the link below.

https://github.com/shinhanbyeol/age-viewer/tree/build/desktop-app-electron

**Comment by Nimra-1234** [comment]
For Frontend :
Wails with React js/Js/Angular
Fyne without these frameworks

**Comment by marodins** [comment]
Wails would be a great framework to use for the frontend. There's a lot of support and it seems that it's a well maintained framework. We can use React with wails and many of the libraries used in the current viewer app. 

One of the most important libraries used in the current frontend app is Cytoscape.js. It's used for the actual visualization of the graph. Although, we may be able to replace this with go-echarts.

**Comment by sarthak-19** [comment]
For the Front-end part, I looked into : 
1. Wails 
2. Fyne
I've mentioned a detailed comparison with pros and cons regarding these [here](https://github.com/apache/age-viewer/issues/87#issuecomment-1373450762) do give it a read and let me know if it would work.
